include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    avoid_classes_with_only_static_members: false
    leading_newlines_in_multiline_strings: false
